package resume

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"time"
)

// Version is one Nexus-generated resume sitting in the library folder.
type Version struct {
	ID         string    `json:"id"`
	CreatedAt  time.Time `json:"created_at"`
	Label      string    `json:"label"` // e.g. target role or "Improved resume"
	TargetRole string    `json:"target_role,omitempty"`
	Template   string    `json:"template,omitempty"` // template id used to render
	PDFPath    string    `json:"pdf_path"`
	MDPath     string    `json:"md_path,omitempty"`
	TeXPath    string    `json:"tex_path,omitempty"`
	JSONPath   string    `json:"json_path,omitempty"`
	Source     string    `json:"source"` // "nexus"
	Notes      string    `json:"notes,omitempty"`
}

type libraryFile struct {
	Versions []Version `json:"versions"`
}

// ResumesDir is ~/.nexus/resumes (created if needed).
func ResumesDir() (string, error) {
	return resumesDir()
}

func libraryPath() (string, error) {
	dir, err := resumesDir()
	if err != nil {
		return "", err
	}
	return filepath.Join(dir, "library.json"), nil
}

// ListVersions returns newest-first generated resumes that still have a PDF on disk.
func ListVersions() ([]Version, error) {
	lp, err := libraryPath()
	if err != nil {
		return nil, err
	}
	data, err := os.ReadFile(lp)
	if err != nil {
		if os.IsNotExist(err) {
			return nil, nil
		}
		return nil, err
	}
	var doc libraryFile
	if err := json.Unmarshal(data, &doc); err != nil {
		return nil, err
	}
	out := make([]Version, 0, len(doc.Versions))
	for _, v := range doc.Versions {
		if v.PDFPath == "" {
			continue
		}
		if _, err := os.Stat(v.PDFPath); err != nil {
			continue
		}
		if v.Source == "" {
			v.Source = "nexus"
		}
		out = append(out, v)
	}
	sort.SliceStable(out, func(i, j int) bool {
		return out[i].CreatedAt.After(out[j].CreatedAt)
	})
	return out, nil
}

// GetVersion returns one generated resume by its library id.
func GetVersion(id string) (Version, error) {
	versions, err := ListVersions()
	if err != nil {
		return Version{}, err
	}
	for _, v := range versions {
		if v.ID == id {
			return v, nil
		}
	}
	return Version{}, fmt.Errorf("no resume version %q in the library", id)
}

// RegisterVersion prepends a generated resume to the library index.
func RegisterVersion(v Version) error {
	if v.ID == "" {
		v.ID = v.CreatedAt.UTC().Format("20060102-150405")
	}
	if v.CreatedAt.IsZero() {
		v.CreatedAt = time.Now()
	}
	if v.Source == "" {
		v.Source = "nexus"
	}
	if v.Label == "" {
		v.Label = "Improved resume"
	}
	lp, err := libraryPath()
	if err != nil {
		return err
	}
	var doc libraryFile
	if data, err := os.ReadFile(lp); err == nil {
		_ = json.Unmarshal(data, &doc)
	}
	// Dedupe by PDF path
	filtered := doc.Versions[:0]
	for _, old := range doc.Versions {
		if filepath.Clean(old.PDFPath) == filepath.Clean(v.PDFPath) {
			continue
		}
		filtered = append(filtered, old)
	}
	doc.Versions = append([]Version{v}, filtered...)
	// Cap history
	if len(doc.Versions) > 30 {
		doc.Versions = doc.Versions[:30]
	}
	data, err := json.MarshalIndent(doc, "", "  ")
	if err != nil {
		return err
	}
	return os.WriteFile(lp, data, 0600)
}

// DisplayLine is a one-line picker label.
func (v Version) DisplayLine() string {
	when := v.CreatedAt.Local().Format("Jan 2, 3:04 PM")
	label := v.Label
	if label == "" {
		label = "Improved resume"
	}
	return when + " · " + label + " · generated by Nexus"
}
