package api

// NexusConfig is the JSON shape the frontend expects — mirrors types/index.ts.
type NexusConfig struct {
	FirstName              string            `json:"firstName"`
	LastName               string            `json:"lastName"`
	Email                  string            `json:"email"`
	Phone                  string            `json:"phone"`
	LinkedinID             string            `json:"linkedinId"`
	ResumePath             string            `json:"resumePath"`
	City                   string            `json:"city"`
	YearsOfExperience      string            `json:"yearsOfExperience"`
	Skills                 []string          `json:"skills,omitempty"`
	TargetJobTitles        string            `json:"targetJobTitles"`
	JobIntent              string            `json:"jobIntent,omitempty"`
	WorkType               string            `json:"workType"`
	TargetLocations        string            `json:"targetLocations"`
	Currency               string            `json:"currency,omitempty"`
	MinSalary              string            `json:"minSalary,omitempty"`
	ProviderKeys           map[string]string `json:"providerKeys,omitempty"`
	LinkedInKey            string            `json:"linkedInKey,omitempty"`
	IndeedKey              string            `json:"indeedKey,omitempty"`
	AIAssist               bool              `json:"aiAssist"`
	AIProvider             string            `json:"aiProvider"`
	AnthropicKey           string            `json:"anthropicKey,omitempty"`
	OpenAIKey              string            `json:"openAIKey,omitempty"`
	GoogleKey              string            `json:"googleKey,omitempty"`
	DeepSeekKey            string            `json:"deepSeekKey,omitempty"`
	GroqKey                string            `json:"groqKey,omitempty"`
	MistralKey             string            `json:"mistralKey,omitempty"`
	TogetherKey            string            `json:"togetherKey,omitempty"`
	OpenRouterKey          string            `json:"openRouterKey,omitempty"`
	XAIKey                 string            `json:"xaiKey,omitempty"`
	AnthropicModel         string            `json:"anthropicModel,omitempty"`
	OpenAIModel            string            `json:"openAIModel,omitempty"`
	GoogleModel            string            `json:"googleModel,omitempty"`
	DeepSeekModel          string            `json:"deepSeekModel,omitempty"`
	GroqModel              string            `json:"groqModel,omitempty"`
	MistralModel           string            `json:"mistralModel,omitempty"`
	TogetherModel          string            `json:"togetherModel,omitempty"`
	OpenRouterModel        string            `json:"openRouterModel,omitempty"`
	XAIModel               string            `json:"xaiModel,omitempty"`
	LocalLLMURL            string            `json:"localLLMURL,omitempty"`
	LocalLLMModel          string            `json:"localLLMModel,omitempty"`
	ApplyConsent           bool              `json:"applyConsent"`
	ApplyConsentAt         string            `json:"applyConsentAt"`
	MaxAppsPerRun          int               `json:"maxAppsPerRun"`
	MaxAppsPerDay          int               `json:"maxAppsPerDay"`
	ApplyDelaySec          int               `json:"applyDelaySec"`
	MinFitScore            int               `json:"minFitScore"`
	CompanyBlocklist       string            `json:"companyBlocklist,omitempty"`
	WorkAuth               string            `json:"workAuth,omitempty"`
	NoticePeriodDays       int               `json:"noticePeriodDays,omitempty"`
	OfficeDaysPerWeek      int               `json:"officeDaysPerWeek,omitempty"`
	CoverLetterMode        string            `json:"coverLetterMode,omitempty"`
	CoverLetterText        string            `json:"coverLetterText,omitempty"`
	OutreachConsent        bool              `json:"outreachConsent,omitempty"`
	MaxEmailsPerDay        int               `json:"maxEmailsPerDay,omitempty"`
	MaxLinkedInPerDay      int               `json:"maxLinkedInPerDay,omitempty"`
	OutreachMode           string            `json:"outreachMode,omitempty"`
	OutreachAutoQueue      bool              `json:"outreachAutoQueue,omitempty"`
	OutreachAICompose      bool              `json:"outreachAICompose,omitempty"`
	OutreachAIReview       bool              `json:"outreachAIReview,omitempty"`
	GmailAppPassword       string            `json:"gmailAppPassword,omitempty"`
	HunterKey              string            `json:"hunterKey,omitempty"`
	ApolloKey              string            `json:"apolloKey,omitempty"`
	LinkedInSessionCookie  string            `json:"linkedInSessionCookie,omitempty"`
	GmailOAuthClientID     string            `json:"gmailOAuthClientID,omitempty"`
	GmailOAuthClientSecret string            `json:"gmailOAuthClientSecret,omitempty"`
	GmailOAuthRefreshToken string            `json:"gmailOAuthRefreshToken,omitempty"`
	DiscordWebhookURL      string            `json:"discordWebhookURL,omitempty"`
	TelegramBotToken       string            `json:"telegramBotToken,omitempty"`
	TelegramChatID         string            `json:"telegramChatID,omitempty"`
	NotifyChannels         []string          `json:"notifyChannels,omitempty"`
	TailorPerJob           bool              `json:"tailorPerJob,omitempty"`
	TailorMaxRounds        int               `json:"tailorMaxRounds,omitempty"`
	ScraperTargets         string            `json:"scraperTargets,omitempty"`
	DailyRunEnabled        bool              `json:"dailyRunEnabled,omitempty"`
	DailyRunAt             string            `json:"dailyRunAt,omitempty"`
	EmailNotifications     bool              `json:"emailNotifications,omitempty"`
	EmailPerJob            bool              `json:"emailPerJob,omitempty"`
}
